### PR TITLE
CartPole Notebook: Migrate to use mujoco to be able to visualize on Colab

### PR DESCRIPTION
**Pull request by traversaro**
Contents of this PR:
* Modify the notebook metadata to request to run on GPU (if possible)
* Switch to use MuJoCo as a visualizer, to be able to render the simulation on Colab

I did not curated the commits as I guess we can just squash and merge.

### CODE REVIEW

**Comment by traversaro** [comment]
cc @flferretti @giulero

**Comment by flferretti** [comment]
Thanks a lot for the PR! I'm having a problem on the visualization as I can see the cartpole only in the first frame of the video, but then it moves outside of the camera framing.
image

Do you know if we can fix this?

**Comment by traversaro** [comment]
We can either change `camera_elem.set("mode", "fixed")` to `trackcom`, or change the camera location. To get the camera location, the best thing is to use the viewer via `python -m mujoco.viewer --mjcf=cartpole.urdf` and copy the camera location from the menu.

**Comment by flferretti** [comment]
There may be something wrong in the visualization as after the first two frames, everything disappear:

| Frame 0 | Frame 1 | Frame 2 |
|:------------------:|:----------------------------:|:------------------:|
| image | image | image |

**Comment by traversaro** [comment]
> There may be something wrong in the visualization as after the first two frames, everything disappear:

Can you fix the initial value instead of using random values so we can debug a reproducible case?

**Comment by flferretti** [comment]
> Can you fix the initial value instead of using random values so we can debug a reproducible case? What are the corresponding jointpos values?

I'm not splitting the key used for the RNG, so the output is always the same: `Array([-0.5674093 ,  0.60824823], dtype=float32)`

**Comment by flferretti** [comment]
Thanks again Silvio, merging

**Pull request merged**
